framework:
    default_locale: 'fr'
    translator:
        paths:
            - '%kernel.project_dir%/translations/fr'
            - '%kernel.project_dir%/translations/en'
        fallbacks:
            - fr
            - en
